export const chatText = {
  getWelcomeMessage: (activeFile, rowCount) => `Hello! I have loaded your database **${activeFile}** containing **${rowCount.toLocaleString()}** transactions. \n\nFeel free to ask me questions in natural language. I will generate SQL queries on the fly, process your data, and show you visual charts or tables.`,
  welcomeTitle: "Retail Conversational Analytics",
  welcomeSubtitle: "Ask questions, run calculations, and build charts directly from your Excel transaction spreadsheets in natural language.",
  removeDatabaseTooltip: "Remove database",
  transactionsLoadedSuffix: "transactions loaded",
  availableColumnsTitle: "Available Columns",
  filterColumnsPlaceholder: "Filter columns...",
  noMatchingColumns: "No matching columns",
  quickSuggestionsTitle: "Quick Suggestions",
  runningSqlPlan: "Running SQL query plan...",
  serverConnectionError: "Sorry, I encountered an error running this query. Please check if your backend server is active.",
  inputPlaceholder: "Ask about transactions, revenue, discounts, regions...",
  footerBranding: "Powered by AlaSQL & Groq — natural language to SQL.",
  tabVisualization: "Visualization",
  tabDataTable: "Data Table",
  tabSqlTrace: "SQL Trace",
  sqlExecutedQueryHeader: "AlaSQL Executed Query",
  noRecordsReturned: "No records returned for this query.",
  suggestedPrompts: [
    "Which store manager has the highest average manual discount amount?",
    "What is the total gross sales by region?",
    "What percentage of transactions had a manual discount?",
    "List the top 5 product categories by gross sales.",
    "Which manual discount reasons are used most frequently?",
    "Average manual discount % for each store in West region",
    "Which stores have the highest manual discounts?",
    "Which regions have the highest manual discounts?",
    "Which store manager gave the lowest manual discount %?",
    "Which items are best selling?",
    "Which items are worst selling?",
    "Top 3 common reasons for manual discounts?",
    "Please display all stores who sold Kids Sandals along with total quantity?",
    "Which store managers approve the highest discounts?",
    "Total discount loss occurred due to manual discounting?"
  ]
};
